version: 2
snapshot:
  widths: [375, 1280]
  minHeight: 1024
  percyCSS: ""
  enableJavaScript: true
  disableShadowDOM: false
discovery:
  networkIdleTimeout: 750
  captureMockedServiceWorker: false
  retry: true
  disallowedHostnames:
    - ws.pusherapp.com
    - socket.pusherapp.com
    - .pusher.com
    - nexus-websocket-a.intercom.io
