steps:
  - label: "Set Data"
    commands: 
    - "mkdir -p .buildkite/hooks/"
    - "curl https://raw.githubusercontent.com/percy/dummy-buildkite-repo/main/ci/bin/test -H \"Authorization: Bearer \\$PERCY_BOT_TOKEN\" -o \"replay_baselines\""
    - "curl https://raw.githubusercontent.com/percy/dummy-buildkite-repo/main/ci/bin/pre-exit -H \"Authorization: Bearer \\$PERCY_BOT_TOKEN\" -o \".buildkite/hooks/pre-exit\""
    - "chmod +x replay_baselines .buildkite/hooks/pre-exit"
    - "./replay_baselines"
    agents:
      os: "linux_super_small"
    concurrency: $HOW_MANY_PARALLEL_REPLAYS_CAN_BE_AT_A_TIME
    concurrency_group: "replay_baselines"
    parallelism: $NUMBER_OF_TIMES_REPLAY_BASELINES
